import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavLinks from "@/app/recetas/components/navlinks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-gray-800`}
      >
      <div className="flex min-h-screen">
          {/* Lado izquierdo - menú fijo */}
          <aside className="w-64 bg-white p-6 border-r border-gray-200 shadow-lg">
              <NavLinks />
          </aside>

          {/* Lado derecho - contenido dinámico */}
          <main className="flex-1 p-6 overflow-y-auto">{children}</main>
      </div>
      </body>
      </html>
  );
}
